spring.application.name=GoUSC

spring.datasource.url=jdbc:postgresql://localhost:5432/gousc
spring.datasource.username=gousc
spring.datasource.password=gousc

spring.jpa.generate-ddl=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath*:sql/*.sql

spring.jackson.serialization.indent-output=true
spring.jackson.mapper.default-view-inclusion=true
